# Generated by Django 3.1.6 on 2021-04-22 22:41

from django.conf import settings
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210420_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(main.models.get_sentinel_user), to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='year',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
